---
driver:
  name: ec2
  tags: {
    "Name": <%= ENV['COOKBOOK'] %>
  }
  aws_ssh_key_id: <%= ENV['EC2_SSH_KEY_ID'] %>
  region: <%= ENV['EC2_REGION'] %>
  availability_zone: <%= ENV['EC2_AZ'] %>
  subnet_id: <%= ENV['EC2_SUBNET_ID'] %>
  security_group_ids: [<%= ENV['EC2_SG'] %>]

provisioner:
  name: chef_zero
  environments_path: test/environments
  client_rb:
    environment: cookbook_ci

transport:
  name: ssh
  username: <%= ENV['SSH_USER'] %>
  ssh_key: <%= ENV['SSH_KEY'] %>

platforms:
  - name: ubuntu
    instance_type: <%= ENV['EC2_INSTANCE_TYPE'] %>
    image_id: <%= ENV['EC2_UBUNTU_AMI'] %>
    block_device_mappings:
      - device_name: /dev/sda1
        ebs:
          delete_on_termination: true
  - name: windows
    instance_type: <%= ENV['EC2_INSTANCE_TYPE'] %>
    image_id: <%= ENV['EC2_AMI'] %>
    driver_config:
      communicator: winrm
    transport:
      name: winrm
    block_device_mappings:
      - device_name: /dev/sda1
        ebs:
          delete_on_termination: true
      - device_name: /dev/sdf
        ebs:
          delete_on_termination: true

suites:
  - name: <%= ENV['COOKBOOK'] %>
    data_bags_path: <%= ENV['CHEF_DATA_BAGS'] %>
    encrypted_data_bag_secret_key_path: <%= ENV['CHEF_SECRET_FILE'] %>
    run_list:
      - recipe[test_docker::default]
